version: "3.8"
services:

# front-end
  docman-react:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: docman-react
    hostname: docman-react
    user: root
    restart: always
    privileged: true
    expose:
      - "8080"
    ports:
      - "8080:80"
    volumes:
      - /home/data/nginx/www:/usr/share/nginx/html
      - /home/data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/data/nginx/conf:/etc/nginx/conf.d
      - /home/data/nginx/logs:/var/log/nginx
    networks:
      - docman-network

# back-end
#  docman:
#    build:
#      context: .
#      dockerfile: Dockerfile.backend
#    container_name: docman
#    hostname: docman
#    user: root
#    restart: always
#    expose:
#      - "8081"
#    ports:
#      - "8081:8888"
#    volumes:
#      - /home/data/docman:/usr/src/app
#    networks:
#      - docman-network

volumes:
  #定义自动创建的卷名
  nginx-vol:
    #false-系统自动创建的卷名,格式为: 目录名_卷名，默认为false; true-使用外部创建的卷面，需要自己手动创建
    external: false

# network
networks:
  docman-network:
    driver: bridge


